name: pypi-publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build release distributions
        run: |
          uv build

      - name: Upload distributions
        run: |
          # Requires UV_PUBLISH_TOKEN to be set
          uv publish
